import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import { packDocx, loadPackage, FIXTURE_PART_SLOTS } from './docx.js';
import { loadAllScenarios, REPO_ROOT } from './scenarios.js';

const checkMode = process.argv.includes('--check');
let drifted = 0;
// Unrecognized input fragments are an authoring error in either mode (packing
// or checking), so they fail the run even when not in --check.
let hardErrors = 0;

// The only `.xml` files recognized under a scenario's `input/`. Anything else
// (a typo'd `comment.xml`, an as-yet-unsupported `header-first.xml`) would be
// silently dropped from the package, so it is a hard error rather than ignored.
const KNOWN_INPUT_XML = new Set<string>([
  'document.xml',
  ...FIXTURE_PART_SLOTS.map((s) => s.fragmentFile),
]);

/**
 * Collect the closed set of optional sibling fragments present under a
 * scenario's `input/` directory, keyed by their fragment file name. Any file
 * outside FIXTURE_PART_SLOTS (including `document.xml` itself) is ignored.
 */
function collectSiblings(scenarioDir: string): Map<string, string> {
  const siblings = new Map<string, string>();
  for (const slot of FIXTURE_PART_SLOTS) {
    const fragmentPath = join(scenarioDir, 'input', slot.fragmentFile);
    if (existsSync(fragmentPath)) {
      siblings.set(slot.fragmentFile, readFileSync(fragmentPath, 'utf8'));
    }
  }
  return siblings;
}

/** Unrecognized `.xml` files under `input/` that would be silently unpacked. */
function unknownInputXml(scenarioDir: string): string[] {
  return readdirSync(join(scenarioDir, 'input'))
    .filter((f) => f.endsWith('.xml') && !KNOWN_INPUT_XML.has(f))
    .sort();
}

/**
 * Compare two packages by DECOMPRESSED part content, not raw zip bytes. The
 * committed `input.docx` is generated by the same `packDocx`, but comparing
 * compressed bytes would couple the check to fflate's exact serialization and
 * the build platform (CI Linux vs. a contributor's machine can emit different
 * DEFLATE output for identical content). Comparing the unzipped part map keeps
 * drift detection portable while still covering every part — the main document,
 * every sibling, `[Content_Types].xml`, and `word/_rels/document.xml.rels`.
 * Returns a human-readable reason on drift, or null when the packages match.
 */
function comparePartMaps(expected: Uint8Array, committed: Uint8Array): string | null {
  const e = loadPackage(expected).parts;
  const a = loadPackage(committed).parts;
  for (const name of [...new Set([...e.keys(), ...a.keys()])].sort()) {
    if (!a.has(name)) return `missing part ${name}`;
    if (!e.has(name)) return `unexpected part ${name}`;
    if (e.get(name) !== a.get(name)) return `part ${name} differs`;
  }
  return null;
}

for (const { manifest, scenarioDir } of loadAllScenarios()) {
  const unknown = unknownInputXml(scenarioDir);
  if (unknown.length > 0) {
    console.error(
      `UNKNOWN ${relative(REPO_ROOT, join(scenarioDir, 'input'))}: unrecognized fragment(s) ${unknown.join(', ')}; ` +
        `only ${[...KNOWN_INPUT_XML].join(', ')} are packed`
    );
    hardErrors++;
    continue;
  }
  const fragment = readFileSync(join(scenarioDir, 'input', 'document.xml'), 'utf8');
  const siblings = collectSiblings(scenarioDir);
  const packagePath = join(scenarioDir, manifest.inputDocumentPath);
  const expected = packDocx(fragment, siblings);
  if (checkMode) {
    if (!existsSync(packagePath)) {
      console.error(`MISSING ${relative(REPO_ROOT, packagePath)}`);
      drifted++;
      continue;
    }
    const reason = comparePartMaps(expected, readFileSync(packagePath));
    if (reason !== null) {
      console.error(
        `DRIFT ${relative(REPO_ROOT, packagePath)}: ${reason}; run 'npm run pack-fixtures'`
      );
      drifted++;
    } else {
      const extra = siblings.size > 0 ? ` (+${siblings.size} sibling part(s))` : '';
      console.log(`OK ${manifest.scenarioId}${extra}`);
    }
  } else {
    writeFileSync(packagePath, expected);
    const extra = siblings.size > 0 ? ` (+${siblings.size} sibling part(s))` : '';
    console.log(`PACKED ${relative(REPO_ROOT, packagePath)}${extra}`);
  }
}

if (checkMode && drifted > 0) {
  console.error(
    `${drifted} fixture package(s) out of sync; run 'npm run pack-fixtures'`
  );
}
if (hardErrors > 0) {
  console.error(`${hardErrors} scenario(s) have unrecognized input fragments`);
}
if (hardErrors > 0 || (checkMode && drifted > 0)) {
  process.exit(1);
}
